### PR TITLE
Updated experiment.m

### PR DESCRIPTION
**Pull request by jcohenadad**
Related to #123

### CODE REVIEW

**Review by gaspardcereza — APPROVED** [review]
Approved

**Comment by po09i** [comment]
Changed load-niftis to output the new format discussed in [issue](https://github.com/shimming-toolbox/shimming-toolbox/issues/102) (x,y,z,echoes,nacqs)

**Comment by jcohenadad** [comment]
@po09i is that easier if we merge that branch now and progressively open new PRs with updates on the experiment.m file?

**Comment by po09i** [comment]
Yes that would be great!

**Pull request merged**
