### PR TITLE
Establish a workflow for processing niftis

### PR DESCRIPTION
**Pull request by po09i**
The purpose of this PR is to establish a workflow for processing niftis.

dicom_to_nifti : Takes unsorted dicoms and processes them using dcm2bids
load_niftis : Uses the bids folder structure to load niftis in the desired format.

The experiment uses those functions to show the workflow.

### CODE REVIEW

**Comment by po09i** [comment]
Notes : 
- What should be done of the README inside the videotape folder that has a lot of info for octave compatibility issues?
- Should I squash rebase into a single commit?

**Review by jcohenadad — APPROVED** [review]
given we are pressed with time and many "brains" have already worked on that branch, i consider it safe to merge

**Comment by po09i** [comment]
What about the README inside the videotape folder @jcohenadad ?

**Comment by jcohenadad** [comment]
> What about the README inside the videotape folder @jcohenadad ?

ah... not good (oversight-- sorry). So:
- get rid of the README
- the chunk about the dependency/procedure goes in the experiment.m 
- the chunk about octave compatibility goes under the wiki (create a new entry "Octave")

that's the best i can think of for now

**Pull request merged**
