### PR TITLE
Setup CI with azure-pipeline and Matlab test suite

### LINKED ISSUE #66: Create testing suite
Here are some options:
- [MoxUnit](https://github.com/MOxUnit/MOxUnit): lightweight unit test framework for Matlab and GNU Octave.
  - pros: octave-compatible --> could be used within Travis
- [Matlab testing suite](https://www.mathworks.com/help/matlab/matlab-unit-test-framework.html?s_tid=CRUX_lftnav)

### LINKED ISSUE #143: CI and doc build
Currently, we have:
- MoxUnits launched by GH actions, launched for each PR
- Azure pipeline for testing and building doc, launched for each PR + merge on master

ideally, we should centralize CI and doc build in Azure, having:
- one pipeline for CI, which runs for new PRs and merge to master
- another pipeline for building docs, which runs for every new merge to master

moreover, @mathieuboudreau has started to deploy unit testing scripts using `runTestSuite()` here https://github.com/shimming-toolbox/shimming-toolbox/pull/127, so i suggest we move to this testing framework (and get rid of MoxUnits, which was initially deployed having Octave compatibility in mind)

### PR DESCRIPTION
**Pull request by po09i**
This PR is to implement Matlab unit tests using azure pipeline and remove MoxUnit tests.

This fixes #143 
This fixes #66

### CODE REVIEW

**Comment by po09i** [comment]
Requested installation of [Matlab CI](https://mathworks.github.io/ci-pilot/migrating.html) on our azure platform.

**Comment by po09i** [comment]
An example of the log for a failed test can be seen [here](https://github.com/shimming-toolbox/shimming-toolbox/runs/828315238). Clicking on `raw output` displays which test failed. 

I noticed the Matlab version used to do the test is 2018. The script uses the first version it sees on the $PATH, Agah needs to have 2018 on the path so I'm looking for a solution to temporarily add it to the path. 

There are reports which are included in the script (test-report and code-coverage report) that seem to only be physically on tristano, I will check how we can output them properly.

**Comment by jcohenadad** [comment]
> The script uses the first version it sees on the $PATH

can't you just point to a specific MATLAB version (with full path to matlab's binary)?

**Comment by po09i** [comment]
> can't you just point to a specific MATLAB version (with full path to matlab's binary)?

I have to take a closer look but my initial thought is no since since the [Matlab azure CI download page](https://marketplace.visualstudio.com/items?itemName=MathWorks.matlab-azure-devops-extension&ssr=false#overview) specifies to change the path to change the Matlab version being used.

**Review by jcohenadad — APPROVED** [review]

**Comment by po09i** [comment]
Opened this [issue](https://github.com/shimming-toolbox/shimming-toolbox/issues/156) for Matlab version and this [issue](https://github.com/shimming-toolbox/shimming-toolbox/issues/157) for reports for future PRs

**Pull request merged**
