### PR TITLE
eao local changes

### PR DESCRIPTION
**Pull request by evaalonsoortiz**

### CODE REVIEW

**Comment by jcohenadad** [comment]
@evaalonsoortiz there are 68 files changed, which makes it difficult for me to review. 

Many of the changes (if not all) are related to a move of files. If you wish to move files, please use `git mv`, so that these files are not considered "new" in the tracking (and therefore the review is less time consuming).

To make the review process easier, I would suggest you close this PR and reopen a new one based on a branch where files are moved using the command `git mv`. Also please, summarize the proposed changes for the PR in the description box (e.g., what are the main functionalities introduced, etc.). Thanks

**Comment by rtopfer** [comment]
@evaalonsoortiz @jcohenadad 
head's up: i have a fairly significant redesign in the works (issue #41 ) for the object model (i.e. the class structure, which all eminates from MaRdI.m)

we can discuss it during Tuesday's meeting, but if you can avoid unnecessary changes (particularly to MaRdI.m) in the next few days that will make the potential merge much easier!

**Comment by jcohenadad** [comment]
> @evaalonsoortiz @jcohenadad
> head's up: i have a fairly significant redesign in the works (issue #41 ) for the object model (i.e. the class structure, which all eminates from MaRdI.m)
> 
> we can discuss it during Tuesday's meeting, but if you can avoid unnecessary changes (particularly to MaRdI.m) in the next few days that will make the potential merge much easier!

@rtopfer sounds good. Could you please already open a PR from your branch (with prefix "(WIP)" in the title) so we are aware of the current developments. Thanks!

**Comment by evaalonsoortiz** [comment]
This PR is being closed because the changes made are already in master.

**Pull request closed without merging**
